language: python

python:
    - "2.7"
    - "pypy"
#    - "3.3" # removed due to issue #128
    - "3.4"
    - "3.5"

install:
    - python setup.py --quiet install

script:
    - nosetests
    - ./test.bash
