language: python

python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"

install:
    - python setup.py --quiet install

script:
    - nosetests
    - cd tests
    - cd simpletest && ./test.bash
    - cd ../issue65 && ./test.sh
